### ISSUE TITLE
预测无法执行

### ISSUE THREAD

**Issue by Dingxiangtao** [KyanChen/RSMamba#10]
04/27 17:03:14 - mmengine - INFO - Because batch augmentations are enabled, the data preprocessor automatically enables the `to_onehot` option to generate one-hot format labels.
Loads checkpoint by local backend from path: weights/RSMamba-b_UC.pth
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
请问是什么原因导致预测无法进行？

**Comment by Dingxiangtao** [comment]
出结果了，但时间很久大概10分钟左右？正常吗

**Comment by Dingxiangtao** [comment]
显卡用的4090

**Comment by Dingxiangtao** [comment]
权重用的是base级别的

**Comment by KyanChen** [comment]
可能没安装mamba-ssm，查看readme中需要安装的库

**Comment by Dingxiangtao** [comment]
安装的有，还是预测时间就是要这么久啊？我换l和h准确率有上升，但预测时间增加的更多

**Comment by KyanChen** [comment]
一张图不应该，你是windows？

**Comment by Dingxiangtao** [comment]
不是啊，在服务器上跑的

**Comment by Dingxiangtao** [comment]
我安装mamba_ssm是用whl文件装的，直接装装不上，会有影响吗？

**Comment by KyanChen** [comment]
验证一下能否导入，在命令行输入python，然后再输入下面语句
from mamba_ssm.ops.selective_scan_interface import mamba_inner_fn, selective_scan_fn
from mamba_ssm.ops.triton.selective_state_update import selective_state_update
from causal_conv1d import causal_conv1d_fn, causal_conv1d_update

**Comment by Dingxiangtao** [comment]
可以导入，没有报错
