### ISSUE TITLE
按照所给方法修改后依然无法导入mmpretrain.rsmamba模块

### ISSUE THREAD

**Issue by caowbincwb** [KyanChen/RSMamba#13]
<img width="650" alt="问题" src="https://github.com/KyanChen/RSMamba/assets/170315121/7c00b451-5fb2-4a20-874e-2cf6f748b417">
同时在安装transformers4.39.2时出现了如下问题
<img width="739" alt="transformers包引起的冲突" src="https://github.com/KyanChen/RSMamba/assets/170315121/9261f790-7902-4e7d-9d62-40f3cb2021b6">
还有关于selective_scan_cuda的问题
<img width="733" alt="问题2" src="https://github.com/KyanChen/RSMamba/assets/170315121/4d8b1c6e-e542-4f78-80e7-2b7d1fa5d33e">
linux平台，cuda118+torch2.0和cuda122+torch2.1均出现以上问题，mmcv版本2.0.0，其余均参照readme安装

**Comment by November666** [comment]
我也是遇到了同样的问题，请问您解决了吗

**Comment by luchaoshi45** [comment]
我用的这个
mamba-ssm                 2.2.2
causal-conv1d             1.4.0
![image](https://github.com/user-attachments/assets/475943ce-0d58-4cac-8563-bc5c3148fb8e)
![image](https://github.com/user-attachments/assets/6e875854-60d4-4f0f-9c9d-17a7e3232054)
![image](https://github.com/user-attachments/assets/e0b02b63-333e-4607-ae56-2af1dd1ab8a3)

**Comment by KyanChen** [comment]
如果无法安装mambassm相关库，参考常见问题
