### ISSUE TITLE
运行变化检测的train.py时报错，'accuracy': Accuracy().to(device=device), TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by mrxmxm** [KyanChen/RSMamba#16]
运行变化检测的train.py时报错，训练图片都提供了，请问怎么解决
![image](https://github.com/user-attachments/assets/39739385-cca3-4387-9687-3149044f38fa)

**Comment by KyanChen** [comment]
查看一下accuray这个类，看报错应该是要增加一个task的参数
