### ISSUE TITLE
请问这个怎么解决

### ISSUE THREAD

**Issue by lzm-01** [KyanChen/RSMamba#18]
<img width="656" alt="屏幕截图 2024-09-10 131721" src="https://github.com/user-attachments/assets/f780fea7-edcd-4ee4-b617-54c0f39e3d09">

**Comment by lzm-01** [comment]
在运行python tools/train.py configs/rsmamba/rsmamba_aid_b.py时

**Comment by KyanChen** [comment]
修改path_to_data

**Comment by lzm-01** [comment]
Note: The data folder of this project provides a small number of image annotation examples for the above datasets.
请问这个项目没有data folder吗？是需要自己去下载dataset吗
