### ISSUE TITLE
Failed to import custom modules from {'imports': 'mmpretrain.rsmamba', 'allow_failed_imports': False},

### ISSUE THREAD

**Issue by yomik-js** [KyanChen/RSMamba#3]
when i run tools/train.py, there is a wrong.

CUDA 11.8
torch 2.1.2
mmcv 2.1.0

发生异常: ImportError
Failed to import custom modules from {'imports': 'mmpretrain.rsmamba', 'allow_failed_imports': False}, the current sys.path is: 
    tools
    /disk0/xxx/home/anaconda3/envs/rsmamba/lib/python311.zip
    /disk0/xxx/home/anaconda3/envs/rsmamba/lib/python3.11
    /disk0/xxx/home/anaconda3/envs/rsmamba/lib/python3.11/lib-dynload
    /disk0/xxx/home/anaconda3/envs/rsmamba/lib/python3.11/site-packages
    tools/..
    /tmp/tmpcn60stfv
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

**Comment by KyanChen** [comment]
是否前面还有其他报错，并查看常见问题

| |
陈科研
博士生
| |
|
北京航空航天大学
13121205596
***@***.***
北京市昌平区北京航空航天大学
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 04/05/2024 23:26 |
| To | KyanChen/RSMamba ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [KyanChen/RSMamba] Failed to import custom modules from {'imports': 'mmpretrain.rsmamba', 'allow_failed_imports': False}, (Issue #3) |

when i run tools/train.py, there is a wrong.

CUDA 11.8
torch 2.1.2
mmcv 2.1.0

发生异常: ImportError
Failed to import custom modules from {'imports': 'mmpretrain.rsmamba', 'allow_failed_imports': False}, the current sys.path is:
tools
/disk0/lcb/home/anaconda3/envs/rsmamba/lib/python311.zip
/disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11
/disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11/lib-dynload
/disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11/site-packages
tools/..
/tmp/tmpcn60stfv
You should set PYTHONPATH to make sys.path include the directory which contains your custom module

**Comment by yomik-js** [comment]
thanks for your reply.  i found out that it was caused by the cuda version of mmcv not matching my actual version. it has now been resolved.

**Comment by StorywithLove** [comment]
pip install -U openmim
mim install mmcv

> thanks for your reply. i found out that it was caused by the cuda version of mmcv not matching my actual version. it has now been resolved.

In addition to doing this, after executing the above install as per the official website, my same problem was solved

**Comment by clear1oveZ** [comment]
> 是否前面还有其他报错，并查看常见问题 | | 陈科研 博士生 | | | 北京航空航天大学 13121205596 ***@***.*** 北京市昌平区北京航空航天大学 | ---- 已回复消息 ---- |低至 |***@***.***> | |日期 |04/05/2024 23：26 | |收件人 |KyanChen/RSMamba ***@***.***> | |抄送 |订阅 ***@***.***> | |主题 |[KyanChen/RSMamba]无法从 {'imports'： 'mmpretrain.rsmamba'， 'allow_failed_imports'： false} 导入自定义模块（问题#3) | 当我运行 tools/train.py 时，出现错误。 CUDA 11.8 的 火炬 2.1.2 MMCV 2.1.0 版本 发生异常： ImportError 无法从 {'imports'： 'mmpretrain.rsmamba'， 'allow_failed_imports'： False} 导入自定义模块，当前 sys.path 为： 工具 /disk0/lcb/home/anaconda3/envs/rsmamba/lib/python311.zip /disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11 /disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11/lib-dynload /disk0/lcb/home/anaconda3/envs/rsmamba/lib/python3.11/site-packages 工具/。。 /tmp/tmpcn60stfv 您应该设置 PYTHONPATH 以使 sys.path 包含包含自定义模块的目录 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

I have the same problem,I try above two methods,but I can not slove it,can you reply  me?please!
