### ISSUE TITLE
训练数据时报错

### ISSUE THREAD

**Issue by wzd88766** [KyanChen/RSMamba#4]
训练数据时报错，怀疑是硬件处理数据时出现的问题，但是配得环境都是符合作者要求的，根据报错说找不到图片，而且每次运行报错的信息都不一样，但都是说找不到图片，图三是运行前期的展示，其他均为运行后产生的报错，实在无能为力，请大佬抽空给予解答，非常感谢！
<img width="1280" alt="Snipaste_2024-04-22_10-10-34" src="https://github.com/KyanChen/RSMamba/assets/151824840/9000020e-50df-478d-8dd0-99a5a39dc240">
<img width="1280" alt="Snipaste_2024-04-22_10-13-11" src="https://github.com/KyanChen/RSMamba/assets/151824840/4fbf97f3-574a-49d8-9cd0-8614433c4c45">
<img width="1280" alt="Snipaste_2024-04-22_10-13-24" src="https://github.com/KyanChen/RSMamba/assets/151824840/4c2935e8-25de-4513-b19b-c410d62c0697">
<img width="1280" alt="Snipaste_2024-04-22_10-13-49" src="https://github.com/KyanChen/RSMamba/assets/151824840/c0e5a489-eea7-46f5-9d43-ebb8d4bc71f2">

**Comment by KyanChen** [comment]
图片放放的位置错了吧

**Comment by wzd88766** [comment]
谢谢你，这个问题已解决。但出现了新的问题，请问笔记本单卡GPU内存为6G运行不了该程序吗，需要多大的内存才可以支持该代码？？

**Comment by KyanChen** [comment]
windows无法加速

**Comment by wzd88766** [comment]
所以必须使用linux吗？？

**Comment by zhangmengmeng-github** [comment]
请问这是怎么解决的？我也是每次运行会这样
