### ISSUE TITLE
数据及相关

### ISSUE THREAD

**Issue by IronmanVsThanos** [KyanChen/RSMamba#6]
您好，很优秀的工作，我是一个新手，我想尝试基于mamba的分割网络，但是我不是很清楚您的工作中数据集组织的具体格式，比如标签如何放置，能提供更多细节吗？谢谢！

**Comment by KyanChen** [comment]
分割可以使用mmseg，然后把分割网络的backbone换成本算法的RSMamba，例如将MMSeg里面的segformer的backbone换成RSMamba

**Comment by IronmanVsThanos** [comment]
> 分割可以使用mmseg，然后把分割网络的backbone换成本算法的RSMamba，例如将MMSeg里面的segformer的backbone换成RSMamba

谢谢！
