### ISSUE TITLE
代码训练时间慢

### ISSUE THREAD

**Issue by wzd88766** [KyanChen/RSMamba#8]
跑了两个多小时，才跑了1/100不到的数据量，是我的配置有问题吗？希望可以得到解答
![Uploading 运行代码.png…]()

**Comment by sadatamit17** [comment]
Hei wzd99766, I have some questions on running the training, can i have a chat with you?

**Comment by wzd88766** [comment]
of course.But I have just started to study this project. I hope I can help you.

**Comment by sadatamit17** [comment]
In paper  actually it said that
"RSMamba’s performance does not rely on extensive data accumulation, but a longer training duration can further lead to substantial performance gains."

**Comment by sadatamit17** [comment]
> of course.But I have just started to study this project. I hope I can help you.

i actually same like you still reading the paper and trying to train and understand, i think you can help me guide how to preparation the data, I am getting some errors, i already get confused. i can share my social contact we can talk through email or whatsaapp.

**Comment by wzd88766** [comment]
Do you have a wechat account?if so ,please add wzd15838760861

**Comment by KyanChen** [comment]
是否安装了mamba-ssm？
