### ISSUE TITLE
FIle Not found error in ubuntu

### ISSUE THREAD

**Issue by sadatamit17** [KyanChen/RSMamba#9]
HI, there thanks for the great contribution, 
There is issue i am encountering on linux 
"FileNotFoundError: lErrno 2l No such file or directory: '/path to data/rsmamba/datainfo/UC/train.txt"
even though i created the file directory or other ways, but still facing the problem. here is a SS of the error.
![Error](https://github.com/KyanChen/RSMamba/assets/102241982/19a24a90-82e6-4218-b470-d96f9f2a5c6a)

**Comment by KyanChen** [comment]
path is error
